# Generated by Django 5.0.3 on 2024-05-13 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empleados', '0001_initial'),
        ('inventario', '0001_initial'),
        ('servicios', '0002_servicio_anticipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_cobro', to='clientes.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_cobro', to='empleados.empleado')),
                ('productos', models.ManyToManyField(related_name='detalles_cobro', to='inventario.producto')),
                ('servicios', models.ManyToManyField(related_name='detalles_cobro', to='servicios.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('detalle_cobro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='cobros.detallecobro')),
            ],
        ),
    ]
