# Generated by Django 5.0.3 on 2024-05-14 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0001_initial'),
        ('inventario', '0001_initial'),
        ('servicios', '0002_servicio_anticipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoEnTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_en_ticket', to='servicios.servicio')),
            ],
        ),
    ]
