# Generated by Django 5.0.3 on 2024-05-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='anticipo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
