# Generated by Django 5.0.3 on 2024-05-14 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
        ('servicios', '0002_servicio_anticipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accionesservicio',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='accionesservicio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accionesservicio',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.empleado'),
        ),
        migrations.AlterField(
            model_name='accionesservicio',
            name='foto_antes',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_antes/'),
        ),
        migrations.AlterField(
            model_name='accionesservicio',
            name='foto_despues',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_despues/'),
        ),
    ]
